FROM actilis/httpd-cgi:centos-latest

MAINTAINER Francois MICAUX <dok-getpdf@actilis.net>

LABEL Vendor="Actilis" \
      License=GPLv3 \
      Version=18.6

RUN yum -y --setopt=tsflags=nodocs install libXrender libXext  fontconfig libfontenc libXfont urw-fonts xz \
 && curl -Ls https://github.com/wkhtmltopdf/wkhtmltopdf/releases/download/0.12.4/wkhtmltox-0.12.4_linux-generic-amd64.tar.xz \
  | tar -C /usr/local --strip-components 1 -xJ   \
 && chown -R root.root /usr/local/{lib,include,share,bin}  \
 && yum clean all && rm -rf /var/cache/yum 

USER root
COPY conf.d/00-site-centos.conf /etc/httpd/conf.d/00-site.conf
COPY site /var/www/html
COPY getpdf-ep.sh /

ENTRYPOINT ["/getpdf-ep.sh"]
CMD ["/usr/bin/supervisord", "-c", "/etc/supervisord.conf"]
